#! /bin/sh

echo Press RETURN to begin ...
read STRING

FFLAGS=-fopenmp f2py3 -c -m fpic_parallel \
precision.f90 constants.f90 io.f90 pic_parallel.f90 -lgomp

echo
echo Press RETURN to exit ...
read STRING
