#! /bin/sh

echo Press RETURN to begin ...
read STRING

f2py3 -c --fcompiler=gnu95 --f90flags="-fopenmp" -lgomp -m fpic_parallel \
precision.f90 constants.f90 io.f90 pic_parallel.f90

echo
echo Press RETURN to exit ...
read STRING
